---
title: 'Leafs Fans: Some Reasons for Optimism'
author: ''
date: '2020-10-31'
slug: leafs-fans-some-reasons-for-optimism
categories: []
tags: []
---

### Reason 1: It's not 2014
And for that matter, it's not 2009 or 2015 either. You may be dissatisfied with the current Leafs playoff success - but hovering over the years below should make you feel better about things. It displays cumulative points over the course of an 82 game season for the Leafs going back to 1999.

<iframe width="100%" height="684" frameborder="0"
  src="https://observablehq.com/embed/@hockeyfan22/multi-line-chart?cell=chart"></iframe>

I wasn't too surprised to see 2015-16 that far down - I can't get P.A Parenteau leading that team in goals out of my head. Of Course, that was Babcock's first season and I can only imagine he enjoyed every second of coaching players like Uncle Leo and Matt Hunwick.

### Reason 2: We've Escaped Cap Hell
Our prayers to Brandon Pridham panned out! We were all doing that right? Well going into the 2020-21 season, the Leafs have managed to make some *gritty* improvements to their bottom six without trading Nylander, despite the insistence from mainstream media. Click through below to see the Leafs salary distribution according to CapFriendly, as well as the other teams from around the NHL.

<iframe width="100%" height="767" frameborder="0"
  src="https://observablehq.com/embed/@hockeyfan22/nhl-salary-cap?cell=viewof+dd1&cell=chart"></iframe>

The names at the bottom of the list are the ones that stand out to me, but I may have seen one too many TSN articles about trading Nylander for cap space. Leafs fans should be excited to have what appears to b a solid bottom 6 on paper without having to move a valuable player.

### Reason 3: The studs are studs
Speaking of which, sometimes it's easy to forget that the Leafs are paying these guys for a reason - it's that they are quite good at hockey. Instead of arguing over the value provided by these contracts - I'll leave to play around with the chart below, which displays the G/60 in all situations for the core.

<iframe width="100%" height="849" frameborder="0"
  src="https://observablehq.com/embed/@hockeyfan22/fancy-radial-bar-chart?cell=viewof+options&cell=chart"></iframe>